name: Weblate Project Setup

on:
  push:
    branches:
      - '**'

jobs:
  post-request:
    runs-on: ubuntu-latest
    environment: 'Weblate env'
    steps:
      - name: Check and create project in Weblate
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          REPO_SLUG=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')

          echo "Checking if project '${REPO_SLUG}' exists..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Token ${{ secrets.WEBLATE_TOKEN }}" \
            "${{ vars.WEBLATE_URL }}/api/projects/${REPO_SLUG}/")

          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Component '${COMPONENT_SLUG}' already exists."
          elif [ "$HTTP_STATUS" -eq 404 ]; then
            echo "⚠️ Project not found. Creating '${REPO_SLUG}'..."
            curl -X POST "${{ vars.WEBLATE_URL }}/api/projects/" \
              -H "Authorization: Token ${{ secrets.WEBLATE_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "name": "'"${REPO_NAME}"'",
                "slug": "'"${REPO_SLUG}"'",
                "web": "https://weblate.com"
              }'
          else
            echo "❌ Unexpected HTTP status: $HTTP_STATUS"
            exit 1
          fi

      - name: Check and create component in Weblate for current branch
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          BRANCH_NAME="${{ github.ref_name }}"
          REPO_SLUG=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
          COMPONENT_SLUG=$(echo "$REPO_SLUG-$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
          PROJECT_COMPONENT="${REPO_SLUG}.${COMPONENT_SLUG}"
      
          echo "Checking if component '${PROJECT_COMPONENT}' exists..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Token ${{ secrets.WEBLATE_TOKEN }}" \
            "${{ vars.WEBLATE_URL }}/api/components/${REPO_SLUG}/${COMPONENT_SLUG}/")
      
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Component '${COMPONENT_SLUG}' already exists."
            INITIALIZING_COMPONENT=false
          elif [ "$HTTP_STATUS" -eq 404 ]; then
            echo "⚠️ Component not found. Creating '${COMPONENT_SLUG}'..."
            curl -X POST "${{ vars.WEBLATE_URL }}/api/projects/${REPO_SLUG}/components/" \
              -H "Authorization: Token ${{ secrets.WEBLATE_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "name": "'"${COMPONENT_SLUG}"'",
                "slug": "'"${COMPONENT_SLUG}"'",
                "project": "'"${REPO_SLUG}"'",
                "repo": "git@github.com:${{ github.repository }}",
                "branch": "'"${BRANCH_NAME}"'",
                "filemask": "'"${{ vars.FILEMASK }} "'",
                "file_format": "po",
                "vcs": "git",
                "new_lang": "none"
              }'
      
            INITIALIZING_COMPONENT=true
          else
            echo "❌ Unexpected HTTP status: $HTTP_STATUS"
            exit 1
          fi
      
          # # Create addon if component was just initialized
          # if [ "$INITIALIZING_COMPONENT" = true ]; then
          #   echo "🔧 Initializing auto-translate addon for component '${COMPONENT_SLUG}'..."
          echo "$INITIALIZING_COMPONENT"
          echo "$INITIALIZING_COMPONENT" = true
      
          curl -X POST "${{ vars.WEBLATE_URL }}/api/components/${REPO_SLUG}/${COMPONENT_SLUG}/addons/" \
            -H "Authorization: Token ${{ secrets.WEBLATE_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "weblate.autotranslate.autotranslate",
              "configuration": {
                "mode": "translate",
                "engines": ["weblate", "weblate-translation-memory"],
                "threshold": 80,
                "auto_source": "mt",
                "filter_type": "todo"
              }
            }'
          # fi
